/**
 * Chinese Review App - Words Module Strings
 *
 * All user-facing text for the words feature (add, review, admin, all pages).
 * Organized by page/section for easy discovery and translation.
 *
 * Last updated: 2026-02-27
 * Maintainer: [name/role]
 */

export const wordsStrings = {
  en: {
    // ============= NAVIGATION =============
    nav: {
      appTitle: "HanziQuest",
      appSubtitle: "Chinese Character Practice for Kids",
      menu: "Menu",
      navigateBetweenPages: "Navigate between pages.",
      addCharacters: "Add Characters",
      allCharacters: "All Characters",
      contentAdmin: "Content Admin",
      aiPrompts: "AI Prompts",
      debug: "Debug Tools",
      dueReview: "Due Review",
      quizResults: "Quiz Results",
      logout: "Logout",
      switchProfile: "Switch Profile",
      changeAvatar: "Change Avatar",
    },

    // ============= GRADING LABELS =============
    grades: {
      again: "Don't remember",
      hard: "Partially know",
      good: "Mostly know",
      easy: "Fully know",
    },

    // ============= SIDEBAR STATS =============
    sidebar: {
      totalCharacters: "Total characters:",
      dueNow: "Due now:",
      avgFamiliarity: "Avg familiarity:",
    },

    // ============= ADD PAGE =============
    add: {
      pageTitle: "Add Characters",
      pageDescription:
        "Add Chinese characters only (single characters). Batch input is supported with commas, spaces, or line breaks.",
      inputPlaceholder: "Batch characters (e.g. 你, 好 学 习)",
      submitButton: "Batch Add Characters",
      noInput: "Please enter Chinese characters.",
      onlyHanzi: "Only Chinese characters are allowed.",
      noNew: "No new characters were added.",
      partialSuccess: "Added {count} character(s), skipped {skipped} existing.",
      allSuccess: "Added {count} character(s).",
    },

    // ============= REVIEW PAGE (DUE) =============
    due: {
      pageTitle: "Due Characters",
      dueNowLabel: "Due now:",
      startFlashcard: "Start flashcard review",
      startFillTest: "Start fill-test review",
      loading: "Loading due characters...",
      noCharacters: "No due characters right now.",
      reviewTestSessions: {
        title: "Test Sessions",
        empty: "No packaged test sessions yet.",
        createdAt: "Created",
        targets: "Packaged targets",
        quizReady: "Quiz-ready characters",
        action: "Action",
        start: "Start session",
        delete: "Delete session",
        deleting: "Deleting...",
        disabledNoQuizReady: "No quiz-ready characters in this session yet.",
        childOnly: "Child only",
        statusCompleted: "Completed session: {name}",
        statusMissing: "This test session is no longer available.",
        statusChildOnly: "Only child profiles can start a packaged test session.",
        statusInvalid: "This test session is blocked because the packaged character data is invalid.",
        statusEmpty: "This test session has no packaged characters to review.",
        statusNoQuizReady: "This test session has no quiz-ready characters yet.",
        confirmDelete: "Delete the whole test session \"{name}\"?",
        deleteSuccess: "Deleted test session: {name}",
        deleteError: "Could not delete test session: {name}",
      },
      table: {
        character: "Character",
        nextReviewDate: "Next Review Date",
        familiarity: "Familiarity",
        action: "Action",
        flashcard: "Flashcard",
        fillTest: "Fill test",
      },
      sortButtons: {
        sort: "Sort",
      },
    },

    // ============= FLASHCARD REVIEW PAGE =============
    flashcard: {
      pageTitle: "Flashcard Review",
      progress: "Character {current} of {total}",
      stopButton: "Stop flashcards",
      noActiveSession: "Please start a flashcard review from the due-character actions above.",
      revealButton: "Show Pinyin",
      hideButton: "Hide Pinyin",
      revealPrompt: "Show pinyin before grading this card.",
      loadingDict: "Loading dictionary details...",
      noDictData:
        "Could not load dictionary data for this card. You can still grade the review.",
      loadingContent: "Loading saved content...",
      noPronunciations: "(no pronunciation explanations)",
      noCharacterLoaded: "No flashcard character loaded.",
      noBrowserWarning: "Please use a modern browser to see flashcard details.",
      pronounciation: {
        prefix: "Reading",
        notAvailable: "(not available)",
        noSavedContent: "No saved content yet. Preload and save from Content Admin.",
        noMeanings: "(no suitable meanings generated)",
      },
      meaning: {
        prefix: "Meaning",
        examplePrefix: "Example: ",
      },
      card: {
        showDetailsButton: "Show Details",
        hideDetailsButton: "Hide Details",
        noPhraseIncluded: "No phrases included for testing",
      },
      navigation: {
        first: "First",
        previous: "Previous",
        next: "Next",
        end: "End",
      },
      summary: {
        title: "Last Flashcard Summary",
        charactersReviewed: "Characters reviewed:",
      },
      reviewTestSession: {
        activeSession: "Test session: {name} ({count} characters)",
        startQuizButton: "Start quiz",
      },
    },

    // ============= FILL-TEST REVIEW PAGE =============
    fillTest: {
      pageTitle: "Fill Test Quiz",
      dueNowLabel: "Due now:",
      noFillTests: "currently have no fill test.",
      selectionModes: {
        all: "All due",
        manualSelection: "Manual selection",
        custom: "{count} due characters",
      },
      selectedLabel: "Selected characters: ",
      startButton: "Start fill-test quiz",
      hideLastSummary: "Hide last summary",
      allCharactersSelection: "From fill-test due characters",
      manualTableHeaders: {
        test: "Test",
        hanzi: "Hanzi",
        dateAdded: "Date added",
        dateDue: "Date due",
        nextReviewDate: "Next Review Date",
        familiarity: "Familiarity",
      },
      gameplay: {
        characterProgress: "Character {current} / {total}",
        stopButton: "Stop quiz",
        noQuizCharacterLoaded: "No quiz character loaded.",
        unansweredBlanks: "Unanswered blanks:",
        sentenceLabel: "Sentence {current} / {total}",
        phraseBankHeader: "Phrase Bank",
        dragInstruction: "Drag to a blank, or tap phrase then tap blank.",
        dropPlaceholder: "Drop phrase here",
        clearButton: "Clear",
        submitButton: "Submit answer",
      },
      results: {
        scoreLabel: "Score: {correct}/3, scheduler tier: ",
        nextCharacterButton: "Next character",
        sentenceResult: "Sentence {index}: {result} (chosen: {chosen}, expected: {expected})",
        correct: "correct",
        incorrect: "incorrect",
        emptyChoice: "(empty)",
        finishButton: "Finish quiz",
      },
      summary: {
        title: "Last Fill-Test Summary",
        charactersReviewed: "Characters reviewed:",
        correctBlanks: "correct blanks: ",
        fullyCorrect: "Fully correct:",
        partiallyCorrect: "Partially correct:",
        fullyWrong: "Fully wrong:",
        coinsEarned: "Coins Earned:",
      },
      completionMessage: "Fill-test quiz complete.",
      reviewTestSession: {
        activeSession: "Test session quiz: {name} ({count} characters)",
        completed: "Completed test session: {name}",
        completeError: "Quiz finished, but the test session could not be marked complete: {name}",
        returnToDueReviewButton: "Return to Due Review",
      },
    },

    // ============= QUIZ RESULTS PAGE =============
    results: {
      locale: "en",
      pageTitle: "Quiz Results",
      noSessions: "No quiz sessions yet.",
      goToReviewPage: "Go to Review Page",
      summary: {
        totalSessions: "Total Sessions",
        fullyCorrectPercent: "Fully Correct %",
        failedPercent: "Failed %",
        partiallyCorrectPercent: "Partially Correct %",
        totalCharactersTested: "Total Characters Tested",
        totalDuration: "Total Duration",
        totalCoinsEarned: "Total Coins Earned",
      },
      table: {
        headers: {
          date: "Date",
          fullyCorrectPercent: "Fully Correct %",
          failedPercent: "Failed %",
          partiallyCorrectPercent: "Partially Correct %",
          duration: "Duration",
          testedCount: "Tested Count",
          testedCharacters: "Tested Characters",
          failedCount: "Failed Count",
          failedCharacters: "Failed Characters",
          coinsEarned: "Coins Earned",
        },
        noCharacters: "—",
      },
      clearHistory: {
        button: "Clear History",
        title: "Delete all history?",
        message: "This action cannot be undone. All quiz results will be permanently deleted.",
        confirmButton: "Delete All",
        cancelButton: "Cancel",
      },
      emptyState: {
        heading: "No Results Yet",
        message: "Start a quiz to see your results here.",
        action: "Go to Review Page",
      },
    },

    // ============= CONTENT ADMIN PAGE =============
    admin: {
      pageTitle: "Content Admin",
      pageDescription:
        "Preload and manage meanings, phrases, and examples. Review page reads only saved content.",
      stats: {
        characters: "All Characters",
        allTargets: "All Targets",
        withContent: "Targets with content",
        missingContent: "Targets missing content",
        readyForTesting: "Targets included for testing",
        excludedForTesting: "Targets excluded for testing",
      },
      filterStateOn: " (ON)",
      filterTooltips: {
        characters: "Show all targets.",
        allTargets: "Show all targets.",
        withContent: "Filter table to targets with saved content.",
        missingContent: "Filter table to targets missing content.",
        readyForTesting: "Filter table to targets included for testing.",
        excludedForTesting: "Filter table to targets excluded for testing.",
      },
      buttons: {
        preload: "Generate phrases and examples for all characters (AI)",
        preloading: "Generating...",
        cancelPreload: "Cancel",
        cancellingPreload: "Cancelling...",
        refreshAllPinyin: "Regenerate missing pinyin",
        refreshingAllPinyin: "Regenerating...",
        addToReviewTestSession: "Add to test session",
        batchFillTestToggle: "Target",
        clearReviewTestSelection: "Clear selection",
      },
      buttonTooltips: {
        preload: "Generate content for all characters/pronunciations that are missing content. Estimated wait time: ~2 min (20 words), ~5 min (50 words), ~12 min (100 words).",
        refreshAllPinyin: "Batch regenerate missing pinyin for all saved phrases and examples",
      },
      preloadWarning: "⏱️ Estimated generation time: ~2 min for 20 characters, ~5 min for 50 characters, ~12 min for 100 characters.",
      table: {
        headers: {
          character: "Character",
          pronunciation: "Pronunciation",
          meaningZh: "Meaning",
          meaningEn: "Meaning",
          phrase: "Phrase",
          phrasePinyin: "Phrase Pinyin",
          example: "Example",
          examplePinyin: "Example Pinyin",
          includeInFillTest: "Include in tests",
          actions: "Actions",
        },
        actionButtons: {
          regenerate: "R",
          save: "S",
          clearContent: "C",
          deleteRow: "D",
          delete: "D",
          edit: "E",
          addMeaning: "+ Meaning",
          addPhrase: "+ Phrase",
          saveNew: "Save New",
          cancel: "Cancel",
          fillTestOn: "Test On",
          fillTestOff: "Test Off",
          selectTarget: "Select",
          deselectTarget: "Selected",
        },
        actionTooltips: {
          regenerate: "Regenerate all content",
          save: "Save",
          clearContent: "Clear saved content",
          deleteRow: "Delete this row from Content Admin",
          delete: "Delete saved content",
          editMeaning: "Edit meaning inline",
          addMeaning: "Add meaning for this character/pronunciation",
          addPhrase: "Add phrase under this meaning",
          saveNew: "Save and generate EN meaning + phrase pinyin",
          cancelAdd: "Cancel add",
          fillTestOn: "Exclude this row from test generation",
          fillTestOff: "Include this row in test generation",
          batchFillTestOn: "Exclude all selected targets from test generation",
          batchFillTestOff: "Include all selected targets in test generation",
          regeneratePhrase: "Regenerate phrase and example",
          deletePhrase: "Delete this phrase row",
          regenerateExample: "Regenerate example",
          editExample: "Edit example inline",
          deleteExample: "Delete this example row",
          selectTarget: "Select this target for a packaged test session",
          deselectTarget: "Remove this target from the packaged test session selection",
        },
        confirmDeleteRow:
          "Delete {character} ({pronunciation}) from Content Admin? Saved content for this row will also be removed.",
        cannotDeleteLastPronunciation:
          "You can't delete the last pronunciation for this character from Content Admin. Delete the character from the All Characters page instead.",
        summary: {
          filteredLabel: "Filtered",
          noFiltersApplied: "No filters applied",
          selectedLabel: "Selected",
          separator: " | ",
        },
        selection: {
          selectPage: "Select page",
          selectFiltered: "Select filtered ({count})",
          clear: "Clear",
        },
        placeholders: {
          newMeaning: "Enter new meaning",
          editMeaning: "Edit meaning",
          newPhrase: "Enter phrase (must include \"{char}\")",
          matchingExample: "Enter matching example",
          editExample: "Edit example",
        },
        helper: {
          englishGeneratedOnMeaningSave: "Saving will refresh the English meaning.",
          generatedOnSave: "Pinyin and example will be generated on save.",
        },
        emptyMessages: {
          noContent: "No content yet, add a meaning.",
          addMeaningFirst: "Add meaning first.",
          addMeaningAndPhraseFirst: "Add meaning and phrase first.",
        },
      },
      loading: "Loading admin targets...",
      noTargets: "No targets yet. Add characters first.",
      noVisibleTargets: "No Content Admin rows are visible. Re-add a character to restore deleted rows.",
      preloadingProgress: "Preloading {current}/{total}: {character} / {pronunciation}",
      preloadingBatchProgress: "Preloading {from}\u2013{to} / {total}...",
      preloadResult: "Preload finished. Generated {generated}, skipped {skipped}, failed {failed}.",
      preloadCancelled: "Preload cancelled. Generated {generated}, skipped {skipped}, failed {failed}.",
      messages: {
        saveMeaning: "Saved {character} / {pronunciation}.",
        clearContentSuccess: "Cleared saved content for {character} / {pronunciation}.",
        clearContentError: "Could not clear saved content. Please try again.",
        deleteRowSuccess: "Deleted row for {character} / {pronunciation}.",
        deleteRowError: "Could not delete this row. Please try again.",
        deleteEmpty: "Deleted empty (no content).",
        deleteWithContent: "Deleted with content.",
        noContentForExclude: "Cannot exclude entry with no content.",
        upsertSuccess: "Content upserted.",
        upsertError: "Failed to upsert. Please try again.",
        regeneratePhrase: "Regenerating phrase...",
        regenerateExample: "Regenerating example...",
        saveError: "Could not save. Please try again.",
        deleteError: "Could not delete. Please try again.",
        manualEditRequired: "Please manually add/delete and try again.",
        meaningRequired: "Enter meaning before saving.",
        meaningEditSaved: "Saved meaning {meaning} for {character} / {pronunciation}.",
        meaningEditMerged: "Merged into saved meaning {meaning} for {character} / {pronunciation}.",
        meaningEditError: "Could not save the edited meaning. Please try again.",
        phraseRequired: "Enter a phrase before saving.",
        phraseMustInclude: "Phrase must include {character}.",
        exampleRequired: "Enter an example before saving.",
        exampleMustInclude: "Example must include the phrase.",
        noContentToRefresh: "No saved content to refresh pinyin.",
        pinyinRefreshFinished: "Pinyin refresh finished. Refreshed {refreshed}, failed {failed}.",
        batchFillTestToggleSuccess: "Updated {updated} selected target(s) to {state}.",
        batchFillTestToggleNoEligibleTargets: "Selected targets need saved content before they can be switched.",
        batchFillTestToggleError: "Could not update the selected targets for testing. Please try again.",
        reviewTestSessionNameRequired: "Enter a session name.",
        reviewTestSessionNoSelection: "Select at least one target first.",
        reviewTestSessionDuplicateName: "That session name is already in use.",
        reviewTestSessionCreateSuccess: "Created test session {name} with {count} target(s).",
        reviewTestSessionAppendSuccess: "Added {count} target(s) to test session {name}.",
        reviewTestSessionNoNewTargets: "All selected targets are already in test session {name}.",
        reviewTestSessionCreateError: "Could not create the test session. Please try again.",
      },
      reviewTestSession: {
        selectedCount: "Selected targets: {count}",
        nameLabel: "Session name",
        namePlaceholder: "Enter or reuse a session name",
        createButton: "Save session",
        cancelButton: "Cancel",
      },
      emptyTableMessages: {
        missingContent: "No missing targets.",
        withContent: "No targets with content.",
        readyForTesting: "No targets ready for testing.",
        excludedForTesting: "No targets excluded for testing.",
        allRowsDeleted: "No Content Admin rows are visible. Re-add a character to restore deleted rows.",
        default: "No table data yet. Preload or save content first.",
      },
      filters: {
        title: "Default Filters",
        clearButton: "Clear Filters",
        dueNow: {
          label: "Due now",
          tooltip: "Show only characters due for review now (from their words)",
        },
        tags: {
          label: "Tags",
          placeholder: "Select tags (multi-select)",
          tooltip: "Filter by one or more tags (must have all selected)",
        },
      },
      pagination: {
        pageInfo: "Page {current} of {total}",
        firstButton: "⏮",
        previousButton: "◀",
        nextButton: "▶",
        lastButton: "⏭",
      },
    },

    // ============= ALL CHARACTERS PAGE =============
    all: {
      pageTitle: "All Characters",
      pageDescription: "Character list with review/test counts and familiarity.",
      stats: {
        totalCharacters: "Total Characters",
        timesReviewed: "Times Reviewed",
        timesTested: "Times Tested",
        avgFamiliarity: "Avg Familiarity",
      },
      noCharacters: "No characters yet.",
      filters: {
        title: "Default Filters",
        clearButton: "Clear Filters",
        noMatch: "No characters match the selected filters.",
        dueNow: {
          label: "Due now",
          tooltip: "Show only characters due for review now",
        },
        familiarity: {
          label: "Familiarity",
          operatorLabel: "Operator",
          valueLabel: "Value (0-100)",
          operators: {
            lessThanOrEqual: "≤",
            greaterThanOrEqual: "≥",
          },
          tooltip: "Filter by familiarity level",
        },
        tags: {
          label: "Tags",
          placeholder: "Select tags (multi-select)",
          tooltip: "Filter by one or more tags",
          searchPlaceholder: "Search tags...",
        },
      },
      pagination: {
        itemsPerPage: "Items per page",
        pageInfo: "Page {current} of {total}",
        previousButton: "Previous",
        nextButton: "Next",
        firstButton: "First",
        lastButton: "Last",
      },
      table: {
        summary: {
          filteredLabel: "Filtered",
          noFiltersApplied: "No filters applied",
          selectedLabel: "Selected",
          separator: " | ",
        },
        headers: {
          character: "Character",
          dateAdded: "Date Added",
          reviewCount: "Review Count",
          testCount: "Test Count",
          familiarity: "Familiarity",
          nextReviewDate: "Next Review Date",
          actions: "Actions",
        },
        buttons: {
          reset: "Reset",
          resetting: "Resetting...",
          delete: "Delete",
        },
        tooltips: {
          reset: "Reset as new (Date Added = now)",
          delete: "Delete",
        },
        confirmDeleteWithContent:
          "This character has saved flashcard content. Deleting it will also permanently remove all associated content. Continue?",
      },
    },

    // ============= DEBUG TOOLS PAGE =============
    debug: {
      pageTitle: "Debug Tools",
      pageDescription: "Platform admin only. These actions modify production data.",
      cleanOrphanedTitle: "Clean Orphaned Flashcard Content",
      cleanOrphanedDescription:
        "Finds and deletes flashcard_contents rows with no matching word in the words table. Caused by interrupted preload batches followed by word deletion.",
      runCleanup: "Run Cleanup",
      running: "Running...",
      noOrphans: "\u2705 No orphaned content found. Database is clean.",
      confirmOrphans: (count: number, chars: string) =>
        `Found ${count} orphaned flashcard content record(s) for: ${chars}\n\nDelete all?`,
      deleted: (count: number, chars: string) =>
        `\uD83D\uDDD1\uFE0F Deleted ${count} orphaned record(s): ${chars}`,
      cancelled: "Cancelled.",
      error: (msg: string) => `\u274C Error: ${msg}`,
    },

    // ============= COMMON MESSAGES =============
    common: {
      loading: "Loading...",
      noData: "No data yet.",
      error: "An error occurred.",
      success: "Operation completed successfully.",
      loadError: "Failed to load app data. Please refresh the page or log in again.",
    },
  },

  zh: {
    // ============= NAVIGATION =============
    nav: {
      appTitle: "汉字复习游戏",
      appSubtitle: "专为北美小学生设计",
      menu: "菜单",
      navigateBetweenPages: "在页面之间导航。",
      addCharacters: "添加汉字",
      allCharacters: "全部汉字",
      contentAdmin: "内容管理",
      aiPrompts: "AI提示词",
      debug: "调试工具",
      dueReview: "待复习",
      quizResults: "测验结果",
      logout: "登出",
      switchProfile: "切换用户",
      changeAvatar: "更换头像",
    },

    // ============= GRADING LABELS =============
    grades: {
      again: "不记得了",
      hard: "部分认识",
      good: "基本认识",
      easy: "全部认识",
    },

    // ============= SIDEBAR STATS =============
    sidebar: {
      totalCharacters: "总字数:",
      dueNow: "当前待复习:",
      avgFamiliarity: "平均熟悉度:",
    },

    // ============= ADD PAGE =============
    add: {
      pageTitle: "添加汉字",
      pageDescription: "仅添加汉字（单字），支持批量输入。可使用逗号、空格或换行分隔。",
      inputPlaceholder: "汉字批量输入（如：你, 好 学 习）",
      submitButton: "批量添加汉字",
      noInput: "请输入汉字。",
      onlyHanzi: "只支持添加汉字（单字）。",
      noNew: "没有新增汉字（可能都已存在）。",
      partialSuccess: "已添加 {count} 个汉字，跳过 {skipped} 个已存在字符。",
      allSuccess: "已添加 {count} 个汉字。",
    },

    // ============= REVIEW PAGE (DUE) =============
    due: {
      pageTitle: "待复习汉字",
      dueNowLabel: "当前待复习:",
      startFlashcard: "开始闪卡复习",
      startFillTest: "开始填空测试",
      loading: "正在加载待复习汉字...",
      noCharacters: "当前没有待复习汉字。",
      reviewTestSessions: {
        title: "测验",
        empty: "还没有家长指定的测验。",
        createdAt: "创建时间",
        targets: "家长指定的测验目标",
        quizReady: "可测汉字数",
        action: "操作",
        start: "开始测验",
        delete: "删除测验",
        deleting: "删除中...",
        disabledNoQuizReady: "这个测验里还没有可测汉字。",
        childOnly: "仅限孩子",
        statusCompleted: "已完成测验：{name}",
        statusMissing: "这个测验已不可用。",
        statusChildOnly: "只有孩子档案可以开始家长指定的测验。",
        statusInvalid: "这个测验无法进行，因为家长指定的汉字数据无效。",
        statusEmpty: "这个测验里没有可复习的汉字。",
        statusNoQuizReady: "这个测验里还没有可测汉字。",
        confirmDelete: "要删除整个测验“{name}”吗？",
        deleteSuccess: "已删除测验：{name}",
        deleteError: "删除测验失败：{name}",
      },
      table: {
        character: "汉字",
        nextReviewDate: "下次复习日期",
        familiarity: "熟悉度",
        action: "操作",
        flashcard: "闪卡",
        fillTest: "填空测试",
      },
      sortButtons: {
        sort: "排序",
      },
    },

    // ============= FLASHCARD REVIEW PAGE =============
    flashcard: {
      pageTitle: "闪卡复习",
      progress: "第 {current} 个，共 {total} 个",
      stopButton: "停止闪卡",
      noActiveSession: "请先从上方待复习区域开始闪卡复习。",
      revealButton: "显示拼音",
      hideButton: "隐藏拼音",
      revealPrompt: "评分前请先显示拼音。",
      loadingDict: "正在加载词典详情...",
      noDictData: "无法加载该闪卡的词典数据，但仍可以继续评分。",
      loadingContent: "正在读取已保存内容...",
      noPronunciations: "（无读音释义）",
      noCharacterLoaded: "当前未加载闪卡汉字。",
      noBrowserWarning: "请使用现代浏览器查看闪卡详情。",
      pronounciation: {
        prefix: "读音",
        notAvailable: "（暂无）",
        noSavedContent: "暂无已保存内容，请先在内容管理中预生成并保存。",
        noMeanings: "（暂无可用释义）",
      },
      meaning: {
        prefix: "释义",
        examplePrefix: "例句：",
      },
      card: {
        showDetailsButton: "显示详情",
        hideDetailsButton: "隐藏详情",
        noPhraseIncluded: "未包含任何用于测试的短语",
      },
      navigation: {
        first: "第一个",
        previous: "上一个",
        next: "下一个",
        end: "最后一个",
      },
      summary: {
        title: "上次闪卡总结",
        charactersReviewed: "已复习汉字:",
      },
      reviewTestSession: {
        activeSession: "测验：{name}（{count} 个汉字）",
        startQuizButton: "开始测试",
      },
    },

    // ============= FILL-TEST REVIEW PAGE =============
    fillTest: {
      pageTitle: "填空测试",
      dueNowLabel: "当前待测汉字:",
      noFillTests: "个暂无填空题。",
      selectionModes: {
        all: "全部待测",
        manualSelection: "手动选择",
        custom: "{count} 个待测汉字",
      },
      selectedLabel: "计划测试数量:",
      startButton: "开始填空测试",
      hideLastSummary: "隐藏上次总结",
      allCharactersSelection: "从待测汉字中手动选择",
      manualTableHeaders: {
        test: "测试",
        hanzi: "汉字",
        dateAdded: "添加日期",
        dateDue: "应复习日期",
        nextReviewDate: "下次复习日期",
        familiarity: "熟悉度",
      },
      gameplay: {
        characterProgress: "汉字进度 {current} / {total}",
        stopButton: "停止测试",
        noQuizCharacterLoaded: "当前未加载测试汉字。",
        unansweredBlanks: "未填空白:",
        sentenceLabel: "例句 {current} / {total}",
        phraseBankHeader: "词组库",
        dragInstruction: "拖动到空白处，或点击短语然后点击空白处。",
        dropPlaceholder: "在这里放置短语",
        clearButton: "清空",
        submitButton: "提交答案",
      },
      results: {
        scoreLabel: "得分: {correct}/3, 调度等级: ",
        nextCharacterButton: "下一个汉字",
        sentenceResult: "例句 {index}: {result}（选择: {chosen}，正确: {expected}）",
        correct: "正确",
        incorrect: "错误",
        emptyChoice: "（空）",
        finishButton: "完成测试",
      },
      summary: {
        title: "上次填空总结",
        charactersReviewed: "已测试汉字:",
        correctBlanks: "填空正确: ",
        fullyCorrect: "全部正确:",
        partiallyCorrect: "部分正确:",
        fullyWrong: "全部错误:",
        coinsEarned: "获得金币:",
      },
      completionMessage: "填空测试已完成",
      reviewTestSession: {
        activeSession: "测验：{name}（{count} 个汉字）",
        completed: "已完成测验：{name}",
        completeError: "测验已完成，但无法把测验标记为已完成：{name}",
        returnToDueReviewButton: "返回待复习",
      },
    },

    // ============= 测验结果页面 =============
    results: {
      locale: "zh",
      pageTitle: "测验结果",
      noSessions: "还没有测验记录。",
      goToReviewPage: "前往复习页面",
      summary: {
        totalSessions: "总测验次数",
        fullyCorrectPercent: "全对 %",
        failedPercent: "失败 %",
        partiallyCorrectPercent: "部分正确 %",
        totalCharactersTested: "总共测试汉字",
        totalDuration: "总用时",
        totalCoinsEarned: "总获得金币",
      },
      table: {
        headers: {
          date: "日期",
          fullyCorrectPercent: "全对 %",
          failedPercent: "失败 %",
          partiallyCorrectPercent: "部分正确 %",
          duration: "用时",
          testedCount: "测试数量",
          testedCharacters: "测试汉字",
          failedCount: "失败数量",
          failedCharacters: "失败汉字",
          coinsEarned: "获得金币",
        },
        noCharacters: "—",
      },
      clearHistory: {
        button: "清除历史",
        title: "删除所有测验记录?",
        message: "此操作无法撤销。所有测验结果将被永久删除。",
        confirmButton: "删除全部",
        cancelButton: "取消",
      },
      emptyState: {
        heading: "还没有测验结果",
        message: "开始一次测验来查看您的结果。",
        action: "前往复习页面",
      },
    },

    // ============= CONTENT ADMIN PAGE =============
    admin: {
      pageTitle: "内容管理",
      pageDescription: "预生成并管理闪卡的释义、词组、例句。用户端将直接读取已保存内容。",
      stats: {
        characters: "总汉字",
        allTargets: "全部条目",
        withContent: "有内容的条目",
        missingContent: "缺少内容的条目",
        readyForTesting: "可用于测试的条目",
        excludedForTesting: "不录入题库的条目",
      },
      filterStateOn: " (ON)",
      filterTooltips: {
        characters: "显示所有目标（按字符概览）。",
        allTargets: "显示所有目标（包括有内容的）。",
        withContent: "筛选表格以显示有保存内容的目标。",
        missingContent: "筛选表格以显示缺少内容的目标。",
        readyForTesting: "筛选表格以显示可用于测试的目标。",
        excludedForTesting: "筛选表格以显示已排除测试的目标。",
      },
      buttons: {
        preload: "AI一键生成词组例句",
        preloading: "生成中...",
        cancelPreload: "取消",
        cancellingPreload: "取消中...",
        refreshAllPinyin: "批量生成拼音",
        refreshingAllPinyin: "生成中...",
        addToReviewTestSession: "加入测验",
        batchFillTestToggle: "录入",
        clearReviewTestSelection: "清除选择",
      },
      buttonTooltips: {
        preload: "为所有缺失内容的汉字/发音组合生成内容。预计等待时间：约2分钟（20个汉字）、约5分钟（50个汉字）、约12分钟（100个汉字）。",
        refreshAllPinyin: "批量生成所有已保存短语和例句的缺失拼音",
      },
      preloadWarning: "⏱️ 预计生成时间：20个汉字需约2分钟、50个汉字需约5分钟、100个汉字需约12分钟。",
      table: {
        headers: {
          character: "汉字",
          pronunciation: "读音",
          meaningZh: "释义",
          meaningEn: "释义",
          phrase: "词组",
          phrasePinyin: "词组拼音",
          example: "例句",
          examplePinyin: "例句拼音",
          includeInFillTest: "录入填空题",
          actions: "操作",
        },
        actionButtons: {
          regenerate: "重",
          save: "存",
          clearContent: "清",
          deleteRow: "删",
          delete: "删",
          edit: "编",
          addMeaning: "+ 释义",
          addPhrase: "+ 词组",
          saveNew: "保存新项",
          cancel: "取消",
          fillTestOn: "录入On",
          fillTestOff: "录入Off",
          selectTarget: "选择",
          deselectTarget: "已选",
        },
        actionTooltips: {
          regenerate: "重新生成全部内容",
          save: "保存",
          clearContent: "清除已保存内容",
          deleteRow: "从内容管理中删除此行",
          delete: "删除已保存内容",
          editMeaning: "行内编辑释义",
          addMeaning: "为该汉字/读音添加释义",
          addPhrase: "在该释义下添加词组",
          saveNew: "保存并生成英文释义和拼音",
          cancelAdd: "取消添加",
          fillTestOn: "从题库中排除此行",
          fillTestOff: "将此行录入题库",
          batchFillTestOn: "把所有已选择目标从题库中排除",
          batchFillTestOff: "把所有已选择目标录入题库",
          regeneratePhrase: "重新生成词组和例句",
          deletePhrase: "删除该词组行",
          regenerateExample: "重新生成例句",
          editExample: "行内编辑例句",
          deleteExample: "删除该例句行",
          selectTarget: "选择这个目标加入家长指定的测验",
          deselectTarget: "把这个目标从家长指定的测验选择中移除",
        },
        confirmDeleteRow:
          "要从内容管理中删除 {character}（{pronunciation}）这一行吗？该行已保存的内容也会一并删除。",
        cannotDeleteLastPronunciation:
          "不能删除这个汉字在内容管理中的最后一个读音条目。请到 全部汉字 页面删除该汉字。",
        summary: {
          filteredLabel: "筛选后",
          noFiltersApplied: "未应用筛选",
          selectedLabel: "已选择",
          separator: " | ",
        },
        selection: {
          selectPage: "选择此页",
          selectFiltered: "选择筛选结果（{count}）",
          clear: "清空",
        },
        placeholders: {
          newMeaning: "输入新释义",
          editMeaning: "编辑释义",
          newPhrase: "输入词组（需包含“{char}”）",
          matchingExample: "输入匹配例句",
          editExample: "编辑例句",
        },
        helper: {
          englishGeneratedOnMeaningSave: "保存时会重新获取英文释义。",
          generatedOnSave: "保存后将自动生成拼音和例句。",
        },
        emptyMessages: {
          noContent: "暂无内容，请添加释义。",
          addMeaningFirst: "请先添加释义。",
          addMeaningAndPhraseFirst: "请先添加释义和词组。",
        },
      },
      loading: "正在加载内容条目...",
      noTargets: "暂无可管理内容（请先添加汉字）",
      noVisibleTargets: "当前没有可见的内容管理条目。重新添加汉字可恢复已删除行。",
      preloadingProgress: "预生成进度 {current}/{total}: {character} / {pronunciation}",
      preloadingBatchProgress: "预生成 {from}\u2013{to} / {total}...",
      preloadResult:
        "预生成完成。生成 {generated} 个，跳过 {skipped} 个，失败 {failed} 个。",
      preloadCancelled: "预生成已取消。生成 {generated} 个，跳过 {skipped} 个，失败 {failed} 个。",
      messages: {
        saveMeaning: "已保存 {character} / {pronunciation}。",
        clearContentSuccess: "已清除 {character} / {pronunciation} 的已保存内容。",
        clearContentError: "清除已保存内容失败。请重试。",
        deleteRowSuccess: "已删除 {character} / {pronunciation} 这一行。",
        deleteRowError: "删除该行失败。请重试。",
        deleteEmpty: "已删除空条目（无内容）。",
        deleteWithContent: "已删除含内容条目。",
        noContentForExclude: "无法排除没有内容的条目。",
        upsertSuccess: "内容已更新。",
        upsertError: "更新失败。请重试。",
        regeneratePhrase: "重新生成词组中...",
        regenerateExample: "重新生成例句中...",
        saveError: "保存失败。请重试。",
        deleteError: "删除失败。请重试。",
        manualEditRequired: "请手动添加/删除后重试。",
        meaningRequired: "请输入释义后再保存。",
        meaningEditSaved: "已保存 {character} / {pronunciation} 的释义：{meaning}。",
        meaningEditMerged: "已将内容合并到现有释义：{meaning}（{character} / {pronunciation}）。",
        meaningEditError: "保存编辑后的释义失败。请重试。",
        phraseRequired: "请输入短语后再保存。",
        phraseMustInclude: "短语需要包含汉字 {character}。",
        exampleRequired: "请输入例句后再保存。",
        exampleMustInclude: "例句需要包含短语。",
        noContentToRefresh: "无保存内容可生成拼音。",
        pinyinRefreshFinished: "拼音生成完成。已生成 {refreshed} 个，失败 {failed} 个。",
        batchFillTestToggleSuccess: "已把 {updated} 个已选目标更新为：{state}。",
        batchFillTestToggleNoEligibleTargets: "已选择的目标需要先有保存内容，才能切换录入状态。",
        batchFillTestToggleError: "批量切换已选择目标的录入状态失败。请重试。",
        reviewTestSessionNameRequired: "请输入测验名称。",
        reviewTestSessionNoSelection: "请先至少选择一个目标。",
        reviewTestSessionDuplicateName: "这个测验名称已经在使用中。",
        reviewTestSessionCreateSuccess: "已创建测验 {name}，共 {count} 个目标。",
        reviewTestSessionAppendSuccess: "已向测验 {name} 添加 {count} 个目标。",
        reviewTestSessionNoNewTargets: "所选目标都已经在测验 {name} 中。",
        reviewTestSessionCreateError: "创建测验失败。请重试。",
      },
      reviewTestSession: {
        selectedCount: "已选择目标：{count}",
        nameLabel: "测验名称",
        namePlaceholder: "输入或复用测验名称",
        createButton: "保存测验",
        cancelButton: "取消",
      },
      emptyTableMessages: {
        missingContent: "没有缺少内容的条目。",
        withContent: "没有有内容的条目。",
        readyForTesting: "没有可用于测试的条目。",
        excludedForTesting: "没有排除测试的条目。",
        allRowsDeleted: "当前没有可见的内容管理条目。重新添加汉字可恢复已删除行。",
        default: "暂无表格数据。请先预生成或保存内容。",
      },
      filters: {
        title: "默认筛选",
        clearButton: "清除筛选",
        dueNow: {
          label: "当前待复习",
          tooltip: "只显示当前待复习的汉字（仅根据其词汇）",
        },
        tags: {
          label: "标签",
          placeholder: "选择标签（多选）",
          tooltip: "按一个或多个标签筛选（必须拥有所有选定标签）",
        },
      },
      pagination: {
        pageInfo: "第 {current} 页，共 {total} 页",
        firstButton: "⏮",
        previousButton: "◀",
        nextButton: "▶",
        lastButton: "⏭",
      },
    },

    // ============= ALL CHARACTERS PAGE =============
    all: {
      pageTitle: "全部汉字",
      pageDescription: "显示所有汉字及其复习/测试计数和熟悉度。",
      stats: {
        totalCharacters: "总汉字数",
        timesReviewed: "已复习次数",
        timesTested: "已测试次数",
        avgFamiliarity: "平均熟悉度",
      },
      noCharacters: "暂无汉字。",
      filters: {
        title: "默认筛选",
        clearButton: "清除筛选",
        noMatch: "没有汉字匹配所选筛选条件。",
        dueNow: {
          label: "当前待复习",
          tooltip: "只显示当前待复习的汉字",
        },
        familiarity: {
          label: "熟悉度",
          operatorLabel: "操作符",
          valueLabel: "值 (0-100)",
          operators: {
            lessThanOrEqual: "≤",
            greaterThanOrEqual: "≥",
          },
          tooltip: "按熟悉度等级筛选",
        },
        tags: {
          label: "标签",
          placeholder: "选择标签（多选）",
          tooltip: "按一个或多个标签筛选",
          searchPlaceholder: "搜索标签...",
        },
      },
      pagination: {
        itemsPerPage: "每页项目数",
        pageInfo: "第 {current} 页，共 {total} 页",
        previousButton: "上一页",
        nextButton: "下一页",
        firstButton: "首页",
        lastButton: "末页",
      },
      table: {
        summary: {
          filteredLabel: "筛选后",
          noFiltersApplied: "未应用筛选",
          selectedLabel: "已选择",
          separator: " | ",
        },
        headers: {
          character: "汉字",
          dateAdded: "添加日期",
          reviewCount: "复习次数",
          testCount: "测试次数",
          familiarity: "熟悉度",
          nextReviewDate: "下次复习日期",
          actions: "操作",
        },
        buttons: {
          reset: "重置",
          resetting: "重置中...",
          delete: "删除",
        },
        tooltips: {
          reset: "重置为新字（添加日期为当前时间）",
          delete: "删除",
        },
        confirmDeleteWithContent:
          "该汉字已有保存的闪卡内容。删除后，相关内容将一并永久移除。是否继续？",
      },
    },

    // ============= 调试工具页面 =============
    debug: {
      pageTitle: "调试工具",
      pageDescription: "仅限平台管理员使用。这些操作将直接修改用户的数据。",
      cleanOrphanedTitle: "清理孤立闪卡内容",
      cleanOrphanedDescription:
        "查找并删除在 words 表中没有匹配汉字的 flashcard_contents 行。通常由预加载批次中断后删除单词所导致。",
      runCleanup: "执行清理",
      running: "执行中...",
      noOrphans: "\u2705 未发现孤立内容，数据库整洁。",
      confirmOrphans: (count: number, chars: string) =>
        `发现 ${count} 条孤立闪卡内容记录，对应汉字：${chars}\n\n确认全部删除？`,
      deleted: (count: number, chars: string) =>
        `\uD83D\uDDD1\uFE0F 已删除 ${count} 条孤立记录：${chars}`,
      cancelled: "已取消。",
      error: (msg: string) => `\u274C 错误：${msg}`,
    },

    // ============= COMMON MESSAGES =============
    common: {
      loading: "正在加载...",
      noData: "暂无数据。",
      error: "发生错误。",
      success: "操作成功完成。",
      loadError: "加载数据失败，请刷新页面或重新登录。",
    },
  },
};
