/**
 * Add Paragraph Strings — Last updated: 2026-08-18
 *
 * Standalone strings file per 0_BUILD_CONVENTIONS.md §4.1 (standalone route,
 * not a workspace-shared extension). Precedent: /words/prompts mounts
 * through the same shared WordsWorkspace/VM architecture yet owns
 * prompts.strings.ts independently.
 */
export const addParagraphStrings = {
  en: {
    pageTitle: "Manage Paragraphs",
    pageDescription:
      "Paste a block of Chinese text. It's split into sentences with known and unknown characters and phrases flagged inline — select the spans you want to add.",
    titleLabel: "Title (optional)",
    titlePlaceholder: "e.g. Chapter 3 reading",
    inputPlaceholder: "Paste Chinese text here…",
    parseButton: "Parse Text",
    reparseButton: "Re-Parse Text",
    submitButton: "Add Selected & Save Paragraph",
    noInput: "Please paste some text first.",
    noHanziContent: "No Chinese characters were found in this text.",
    truncatedNotice: "The pasted text was too long and was shortened to the first {count} characters.",
    noSelectionSaved: "Nothing was selected to add. The paragraph text was still saved.",
    noNew: "No new characters or phrases were added. The paragraph was saved.",
    partialSuccess: "Added {count} item(s), skipped {skipped} already known.",
    allSuccess: "Added {count} item(s).",
    saveError:
      "The paragraph text couldn't be saved, but any selected characters/phrases above were still added. Please try again.",
    tagAssignError: "Items were added, but assigning the tag failed. Please try again.",
    selectionHint: "Click a character, or click and drag across several, to select it. Click again to deselect.",
    selector: {
      legendKnown: "Known",
      legendUnknown: "Unknown",
      legendSelected: "Selected",
    },
    // ============= LIBRARY =============
    library: {
      importNewButton: "+ Import New Paragraph",
      browseLibraryButton: "← Browse saved paragraphs",
      emptyState: "No paragraphs saved yet. Import your first one to get started.",
      noResultsNotice: "No paragraphs match the current filters.",
      untitledLabel: "(Untitled)",
      spanCountLabel: "{count} word(s)/phrase(s) added",
      testModeCountLabel: "{count} test mode(s)",
      continueImportAction: "Continue Import",
      prepFillTestAction: "Prep Fill Test",
      filterTitleLabel: "Search by title",
      filterTitlePlaceholder: "Search titles…",
      filterTagsLabel: "Filter by tags",
      filterTagsPlaceholder: "All tags",
      filterTagsSelectedCount: "{count} tag(s) selected",
      filterTagsSelectAll: "Select all",
      filterTagsClearAll: "Clear all",
      filterTagsNoneOption: "(No tags)",
      filterClearButton: "Clear filters",
    },
    // ============= CONTINUE IMPORT =============
    continueImport: {
      pageTitle: "Continue Import",
      pageDescription:
        "This paragraph's text can't be changed, but you can add more characters or phrases as your family's vocabulary grows, and edit the title.",
      backLink: "← Back to paragraph list",
      saveButton: "Save Changes",
    },
    // ============= TEST MODES =============
    testModes: {
      pageTitle: "Prep Fill Test",
      pageDescription:
        "Choose which already-known words and phrases in this paragraph should become fill-test blanks, and save the selection as a named test mode.",
      backLink: "← Back to paragraph list",
      listEmptyState: "No test modes yet for this paragraph.",
      noEligibleSpansNotice: "This paragraph has no eligible words or phrases yet. Add some first, via Continue Import.",
      newButton: "+ New Test Mode",
      editAction: "Edit",
      deleteAction: "Delete",
      cancelButton: "Cancel",
      nameLabel: "Test mode name",
      namePlaceholder: "e.g. Easy — 3 blanks",
      saveButton: "Save Test Mode",
      blankCountLabel: "{count} blank(s)",
      nameTakenError: "A test mode with this name already exists for this paragraph.",
      emptySelectionError: "Select at least one word or phrase to test.",
      nameRequiredError: "Please enter a name for this test mode.",
      saveError: "Something went wrong saving the test mode. Please try again.",
      createdNotice: "Test mode saved.",
      updatedNotice: "Test mode updated.",
      selector: {
        legendUnknown: "Unknown",
        legendIneligible: "Known, not eligible",
        legendEligible: "Eligible",
        legendSelected: "Blank",
        selectionHint: "Click an eligible (green) word or phrase to turn it into a blank.",
        wordBankTitle: "Blanks",
        wordBankEmpty: "No blanks selected yet.",
        blankMarkerAriaLabel: "Blank {index}",
      },
    },
  },
  zh: {
    pageTitle: "管理短文",
    pageDescription:
      "粘贴一段中文文本，应用会将其拆分为句子，并在文中标出已认识和未认识的汉字与词语——选择你想要添加的部分。",
    titleLabel: "标题（可选）",
    titlePlaceholder: "例如：第三课课文",
    inputPlaceholder: "在此粘贴中文文本…",
    parseButton: "解析文本",
    reparseButton: "重新解析文本",
    submitButton: "添加所选内容并保存短文",
    noInput: "请先粘贴一些文本。",
    noHanziContent: "未在此文本中找到中文字符。",
    truncatedNotice: "粘贴的文本过长，已截短为前 {count} 个字符。",
    noSelectionSaved: "未选择任何内容添加，短文文本仍已保存。",
    noNew: "没有添加新的汉字或词语，短文已保存。",
    partialSuccess: "已添加 {count} 项，跳过 {skipped} 项已存在内容。",
    allSuccess: "已添加 {count} 项。",
    saveError: "短文文本保存失败，但上方已选中的汉字/词语仍已添加。请重试。",
    tagAssignError: "内容已添加，但标签分配失败。请重试。",
    selectionHint: "点击一个汉字，或点击并拖动经过多个汉字来选择；再次点击可取消选择。",
    selector: {
      legendKnown: "已认识",
      legendUnknown: "未认识",
      legendSelected: "已选择",
    },
    // ============= LIBRARY =============
    library: {
      importNewButton: "＋ 导入新短文",
      browseLibraryButton: "← 浏览已保存的短文",
      emptyState: "还没有保存的短文，先导入第一篇吧。",
      noResultsNotice: "没有短文匹配当前筛选条件。",
      untitledLabel: "（无标题）",
      spanCountLabel: "已添加 {count} 个汉字/词语",
      testModeCountLabel: "{count} 个测试模式",
      continueImportAction: "继续导入",
      prepFillTestAction: "准备填空测试",
      filterTitleLabel: "按标题搜索",
      filterTitlePlaceholder: "搜索标题…",
      filterTagsLabel: "按标签筛选",
      filterTagsPlaceholder: "全部标签",
      filterTagsSelectedCount: "已选择 {count} 个标签",
      filterTagsSelectAll: "全选",
      filterTagsClearAll: "清除全部",
      filterTagsNoneOption: "（无标签）",
      filterClearButton: "清除筛选",
    },
    // ============= CONTINUE IMPORT =============
    continueImport: {
      pageTitle: "继续导入",
      pageDescription: "此短文的正文无法更改，但你可以随着家庭词库的增长添加更多汉字或词语，并编辑标题。",
      backLink: "← 返回短文列表",
      saveButton: "保存更改",
    },
    // ============= TEST MODES =============
    testModes: {
      pageTitle: "准备填空测试",
      pageDescription: "选择此短文中已认识的汉字和词语作为填空测试的空格，并将所选内容保存为一个命名的测试模式。",
      backLink: "← 返回短文列表",
      listEmptyState: "此短文还没有测试模式。",
      noEligibleSpansNotice: "此短文还没有符合条件的汉字或词语，请先通过继续导入添加。",
      newButton: "＋ 新建测试模式",
      editAction: "编辑",
      deleteAction: "删除",
      cancelButton: "取消",
      nameLabel: "测试模式名称",
      namePlaceholder: "例如：简单 — 3个空格",
      saveButton: "保存测试模式",
      blankCountLabel: "{count} 个空格",
      nameTakenError: "此短文已存在同名的测试模式。",
      emptySelectionError: "请至少选择一个汉字或词语进行测试。",
      nameRequiredError: "请输入此测试模式的名称。",
      saveError: "保存测试模式时出现问题，请重试。",
      createdNotice: "测试模式已保存。",
      updatedNotice: "测试模式已更新。",
      selector: {
        legendUnknown: "未认识",
        legendIneligible: "已认识，不符合条件",
        legendEligible: "符合条件",
        legendSelected: "空格",
        selectionHint: "点击一个符合条件（绿色）的汉字或词语，将其变为空格。",
        wordBankTitle: "空格列表",
        wordBankEmpty: "尚未选择任何空格。",
        blankMarkerAriaLabel: "空格 {index}",
      },
    },
  },
};
