-- Add the "vinegar" ingredient and link it into "noodle"'s
-- special ingredients.
--
-- Generated by the add-ingredient skill. Scoped deliberately: this only
-- inserts the one new shop_ingredient_prices row and updates
-- shop_recipes.special_ingredient_slots /
-- special_ingredient_slots_i18n for slug = 'noodle' --
-- it does not touch any other recipe or ingredient row, unlike a full
-- export-shop-content-patch.mjs snapshot.
--
-- NOT verified against production's current state for slug = 'noodle'.
-- The appended ingredient array below reflects DEV's state at the time this
-- file was generated. If prod has diverged on this specific recipe since
-- then, review this diff carefully before running db:push:prod -- it will
-- overwrite prod's base/special ingredient list for this recipe with the
-- array below, not merge with whatever prod currently has.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'vinegar',
  2,
  '{"en":"Vinegar","zh":"醋"}'::jsonb,
  '/ingredients/vinegar.png'
)
on conflict (ingredient_key) do nothing;

update shop_recipes
set
  special_ingredient_slots = '[{"name":"Tomato","quantity":1,"ingredientKey":"tomato"},{"name":"Egg","quantity":1,"ingredientKey":"egg"},{"name":"Pork Liver","quantity":1,"ingredientKey":"pork-liver"},{"name":"Soy Sauce","quantity":1,"ingredientKey":"soy-sauce"},{"ingredientKey":"vinegar","name":"Vinegar","quantity":1}]'::jsonb,
  special_ingredient_slots_i18n = '{"en":[{"name":"Tomato","quantity":1,"ingredientKey":"tomato"},{"name":"Egg","quantity":1,"ingredientKey":"egg"},{"name":"Pork Liver","quantity":1,"ingredientKey":"pork-liver"},{"name":"Soy Sauce","quantity":1,"ingredientKey":"soy-sauce"},{"ingredientKey":"vinegar","name":"Vinegar","quantity":1}],"zh":[{"name":"番茄","quantity":1,"ingredientKey":"tomato"},{"name":"鸡蛋","quantity":1,"ingredientKey":"egg"},{"name":"猪肝","quantity":1,"ingredientKey":"pork-liver"},{"name":"酱油","quantity":1,"ingredientKey":"soy-sauce"},{"ingredientKey":"vinegar","name":"醋","quantity":1}]}'::jsonb,
  updated_at = now()
where slug = 'noodle';

commit;
