-- Add the "soy-sauce" ingredient and link it into "fried-egg-over-rice"'s
-- special ingredients.
--
-- Generated by the add-ingredient skill. Scoped deliberately: this only
-- inserts the one new shop_ingredient_prices row and updates
-- shop_recipes.special_ingredient_slots /
-- special_ingredient_slots_i18n for slug = 'fried-egg-over-rice' --
-- it does not touch any other recipe or ingredient row, unlike a full
-- export-shop-content-patch.mjs snapshot.
--
-- NOT verified against production's current state for slug = 'fried-egg-over-rice'.
-- The appended ingredient array below reflects DEV's state at the time this
-- file was generated. If prod has diverged on this specific recipe since
-- then, review this diff carefully before running db:push:prod -- it will
-- overwrite prod's base/special ingredient list for this recipe with the
-- array below, not merge with whatever prod currently has.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'soy-sauce',
  2,
  '{"en":"Soy Sauce","zh":"酱油"}'::jsonb,
  null
)
on conflict (ingredient_key) do nothing;

update shop_recipes
set
  special_ingredient_slots = '[{"name":"Tofu","quantity":1,"ingredientKey":"tofu"},{"name":"Peppercorn","quantity":1,"ingredientKey":"peppercorn"},{"name":"Fresh ground pork","quantity":1,"ingredientKey":"pork-filling"},{"ingredientKey":"soy-sauce","name":"Soy Sauce","quantity":1}]'::jsonb,
  special_ingredient_slots_i18n = '{"en":[{"name":"Tofu","quantity":1,"ingredientKey":"tofu"},{"name":"Peppercorn","quantity":1,"ingredientKey":"peppercorn"},{"name":"Fresh ground pork","quantity":1,"ingredientKey":"pork-filling"},{"ingredientKey":"soy-sauce","name":"Soy Sauce","quantity":1}],"zh":[{"name":"豆腐","quantity":1,"ingredientKey":"tofu"},{"name":"花椒","quantity":1,"ingredientKey":"peppercorn"},{"name":"新鲜猪肉馅","quantity":1,"ingredientKey":"pork-filling"},{"ingredientKey":"soy-sauce","name":"酱油","quantity":1}]}'::jsonb,
  updated_at = now()
where slug = 'fried-egg-over-rice';

commit;
