-- Create the new "popcorn-chicken" food (shop_recipes row), plus its new ingredient catalog row(s).
--
-- Generated by the add-food skill. Scoped deliberately: this only inserts
-- one new shop_recipes row and the new ingredient row(s) it introduces -- it does not touch any other recipe or ingredient row.
--
-- NOT separately verified against production for slug = 'popcorn-chicken'.
-- The recipe insert is a plain INSERT, so it only fails (not silently
-- overwrites) if production already has a row with this slug -- but
-- confirm that's actually true before running db:push:prod. Any new
-- ingredient upserts below use ON CONFLICT DO NOTHING, so they're safe
-- to run even if prod already has that ingredient key from elsewhere.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

-- New ingredient catalog rows this food introduces:
insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'chicken-thigh',
  7,
  '{"en":"Chicken Thigh","zh":"鸡腿肉"}'::jsonb,
  '/ingredients/chicken-thigh.png'
)
on conflict (ingredient_key) do nothing;

insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'basil-leaves',
  2,
  '{"en":"Basil Leaves","zh":"九层塔"}'::jsonb,
  '/ingredients/basil-leaves.png'
)
on conflict (ingredient_key) do nothing;

insert into shop_recipes (
  slug, title, title_i18n, display_order, is_active,
  intro, intro_i18n, unlock_cost_coins,
  base_ingredients, base_ingredients_i18n,
  special_ingredient_slots, special_ingredient_slots_i18n,
  variant_icon_rules, cook_method, food_type
)
values (
  'popcorn-chicken',
  'Popcorn Chicken',
  '{"en":"Popcorn Chicken","zh":"盐酥鸡"}'::jsonb,
  13,
  true,
  'Bite-sized chicken thigh fried golden and crispy, tossed with salt and fragrant basil leaves. A night-market favorite you can''t stop snacking on!',
  '{"en":"Bite-sized chicken thigh fried golden and crispy, tossed with salt and fragrant basil leaves. A night-market favorite you can''t stop snacking on!","zh":"一口大小的鸡腿肉炸得金黄酥脆,撒上盐和香喷喷的九层塔。夜市里最受欢迎的小吃,一口接一口停不下来!"}'::jsonb,
  25,
  '[{"ingredientKey":"chicken-thigh","name":"Chicken Thigh","quantity":1},{"ingredientKey":"basil-leaves","name":"Basil Leaves","quantity":1},{"ingredientKey":"salt","name":"Salt","quantity":1},{"ingredientKey":"soy-sauce","name":"Soy Sauce","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"chicken-thigh","name":"Chicken Thigh","quantity":1},{"ingredientKey":"basil-leaves","name":"Basil Leaves","quantity":1},{"ingredientKey":"salt","name":"Salt","quantity":1},{"ingredientKey":"soy-sauce","name":"Soy Sauce","quantity":1}],"zh":[{"ingredientKey":"chicken-thigh","name":"鸡腿肉","quantity":1},{"ingredientKey":"basil-leaves","name":"九层塔","quantity":1},{"ingredientKey":"salt","name":"盐","quantity":1},{"ingredientKey":"soy-sauce","name":"酱油","quantity":1}]}'::jsonb,
  '[]'::jsonb,
  '{"en":[],"zh":[]}'::jsonb,
  '[{"match":[],"iconPath":"/rewards/popcorn-chicken_plain.png"}]'::jsonb,
  'stove',
  'hotmeal'
);

commit;
