-- Create the new "fried-egg-over-rice" food (shop_recipes row), plus its new ingredient catalog row(s).
--
-- Generated by the add-food skill. Scoped deliberately: this only inserts
-- one new shop_recipes row and the new ingredient row(s) it introduces -- it does not touch any other recipe or ingredient row.
--
-- NOT separately verified against production for slug = 'fried-egg-over-rice'.
-- The recipe insert is a plain INSERT, so it only fails (not silently
-- overwrites) if production already has a row with this slug -- but
-- confirm that's actually true before running db:push:prod. Any new
-- ingredient upserts below use ON CONFLICT DO NOTHING, so they're safe
-- to run even if prod already has that ingredient key from elsewhere.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

-- New ingredient catalog rows this food introduces:
insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'scallions',
  1,
  '{"en":"Scallions","zh":"葱"}'::jsonb,
  '/ingredients/scallions.png'
)
on conflict (ingredient_key) do nothing;

insert into shop_recipes (
  slug, title, title_i18n, display_order, is_active,
  intro, intro_i18n, unlock_cost_coins,
  base_ingredients, base_ingredients_i18n,
  special_ingredient_slots, special_ingredient_slots_i18n,
  variant_icon_rules, cook_method, food_type
)
values (
  'fried-egg-over-rice',
  'Fried Egg over Rice',
  '{"en":"Fried Egg over Rice","zh":"煎蛋盖饭"}'::jsonb,
  12,
  true,
  'A warm bowl of rice topped with two soft fried eggs and fresh scallions, simple, comforting, and always hits the spot.',
  '{"en":"A warm bowl of rice topped with two soft fried eggs and fresh scallions, simple, comforting, and always hits the spot.","zh":"一碗热腾腾的米饭，配上两个软嫩煎蛋和新鲜葱花，简单又暖心，怎么吃都不腻。"}'::jsonb,
  25,
  '[{"ingredientKey":"cooked-rice","name":"Steam Rice","quantity":1},{"ingredientKey":"egg","name":"Egg","quantity":2},{"ingredientKey":"scallions","name":"Scallions","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"cooked-rice","name":"Steam Rice","quantity":1},{"ingredientKey":"egg","name":"Egg","quantity":2},{"ingredientKey":"scallions","name":"Scallions","quantity":1}],"zh":[{"ingredientKey":"cooked-rice","name":"米饭","quantity":1},{"ingredientKey":"egg","name":"鸡蛋","quantity":2},{"ingredientKey":"scallions","name":"葱","quantity":1}]}'::jsonb,
  '[]'::jsonb,
  '{"en":[],"zh":[]}'::jsonb,
  '[{"match":[],"iconPath":"/rewards/fried-egg-over-rice_plain.png"}]'::jsonb,
  'stove',
  'hotmeal'
);

commit;
