-- Add a named variant rule (match = [peppercorn,pork-filling,soy-sauce,tofu]) to "fried-egg-over-rice"'s
-- variant_icon_rules.
--
-- Generated by the add-food-variation skill. Scoped deliberately: this only
-- updates shop_recipes.variant_icon_rules for slug = 'fried-egg-over-rice' -- it
-- does not touch any other recipe, ingredient, or column, and assumes every
-- ingredient key in the match was already linked to this recipe's
-- special_ingredient_slots by a prior (or companion) migration.
--
-- NOT verified against production's current variant_icon_rules for slug = 'fried-egg-over-rice'.
-- The base array below reflects DEV's state at the time this file was
-- generated. If prod has diverged on this recipe's variant rules since
-- then, review this diff carefully before running db:push:prod -- it will
-- overwrite prod's variant_icon_rules for this recipe with the array
-- below, not merge with whatever prod currently has.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

update shop_recipes
set
  variant_icon_rules = '[{"match":[],"iconPath":"/rewards/fried-egg-over-rice_plain.png"},{"match":["peppercorn","pork-filling","soy-sauce","tofu"],"iconPath":"/rewards/fried-egg-over-rice_mapo-tofu.png","waivedBaseIngredientKeys":["egg"],"titleI18n":{"en":"Mapo Tofu over Rice","zh":"麻婆豆腐盖饭"}}]'::jsonb,
  updated_at = now()
where slug = 'fried-egg-over-rice';

commit;
