-- Create the new "pancake" food (shop_recipes row), plus its new ingredient catalog row(s).
--
-- Generated by the add-food skill. Scoped deliberately: this only inserts
-- one new shop_recipes row and the new ingredient row(s) it introduces -- it does not touch any other recipe or ingredient row.
--
-- NOT separately verified against production for slug = 'pancake'.
-- The recipe insert is a plain INSERT, so it only fails (not silently
-- overwrites) if production already has a row with this slug -- but
-- confirm that's actually true before running db:push:prod. Any new
-- ingredient upserts below use ON CONFLICT DO NOTHING, so they're safe
-- to run even if prod already has that ingredient key from elsewhere.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

-- New ingredient catalog rows this food introduces:
insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'syrup',
  3,
  '{"en":"Syrup","zh":"糖浆"}'::jsonb,
  '/ingredients/syrup.png'
)
on conflict (ingredient_key) do nothing;

insert into shop_recipes (
  slug, title, title_i18n, display_order, is_active,
  intro, intro_i18n, unlock_cost_coins,
  base_ingredients, base_ingredients_i18n,
  special_ingredient_slots, special_ingredient_slots_i18n,
  variant_icon_rules, cook_method, food_type
)
values (
  'pancake',
  'Pancake',
  '{"en":"Pancake","zh":"松饼"}'::jsonb,
  10,
  true,
  'Fluffy golden pancakes, stacked and ready to eat.',
  '{"en":"Fluffy golden pancakes, stacked and ready to eat.","zh":"松软金黄的松饼，一叠叠新鲜出炉。"}'::jsonb,
  20,
  '[{"ingredientKey":"flour","name":"Flour","quantity":2},{"ingredientKey":"egg","name":"Egg","quantity":1},{"ingredientKey":"milk","name":"Milk","quantity":1},{"ingredientKey":"butter","name":"Butter","quantity":1},{"ingredientKey":"syrup","name":"Syrup","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"flour","name":"Flour","quantity":2},{"ingredientKey":"egg","name":"Egg","quantity":1},{"ingredientKey":"milk","name":"Milk","quantity":1},{"ingredientKey":"butter","name":"Butter","quantity":1},{"ingredientKey":"syrup","name":"Syrup","quantity":1}],"zh":[{"ingredientKey":"flour","name":"面粉","quantity":2},{"ingredientKey":"egg","name":"鸡蛋","quantity":1},{"ingredientKey":"milk","name":"牛奶","quantity":1},{"ingredientKey":"butter","name":"黄油","quantity":1},{"ingredientKey":"syrup","name":"糖浆","quantity":1}]}'::jsonb,
  '[{"ingredientKey":"strawberry","name":"Strawberry","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"strawberry","name":"Strawberry","quantity":1}],"zh":[{"ingredientKey":"strawberry","name":"草莓","quantity":1}]}'::jsonb,
  '[{"match":[],"iconPath":"/rewards/pancake_plain.png"},{"match":["strawberry"],"iconPath":"/rewards/pancake_strawberry_wink.png","titleI18n":{"en":"Strawberry Pancake","zh":"草莓松饼"}}]'::jsonb,
  'stove',
  'hotmeal'
);

commit;
