-- Add a named variant rule (match = [pork-liver,soy-sauce,vinegar]) to "noodle"'s
-- variant_icon_rules.
--
-- Generated by the add-food-variation skill. Scoped deliberately: this only
-- updates shop_recipes.variant_icon_rules for slug = 'noodle' -- it
-- does not touch any other recipe, ingredient, or column, and assumes every
-- ingredient key in the match was already linked to this recipe's
-- special_ingredient_slots by a prior (or companion) migration.
--
-- NOT verified against production's current variant_icon_rules for slug = 'noodle'.
-- The base array below reflects DEV's state at the time this file was
-- generated. If prod has diverged on this recipe's variant rules since
-- then, review this diff carefully before running db:push:prod -- it will
-- overwrite prod's variant_icon_rules for this recipe with the array
-- below, not merge with whatever prod currently has.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

update shop_recipes
set
  variant_icon_rules = '[{"match":[],"iconPath":"/rewards/noodle_plain.png"},{"match":["egg","tomato"],"iconPath":"/rewards/noodle_tomato-egg.png","titleI18n":{"en":"Tomato Egg Noodles","zh":"番茄鸡蛋面"}},{"match":["pork-liver","soy-sauce","vinegar"],"iconPath":"/rewards/noodle_pork-liver.png","titleI18n":{"en":"Pork Liver Noodles","zh":"猪肝面"}}]'::jsonb,
  updated_at = now()
where slug = 'noodle';

commit;
