-- Add the "pork-filling" ingredient and link it into "zongzi"'s
-- special ingredients.
--
-- Generated by the add-ingredient skill. Scoped deliberately: this only
-- inserts the one new shop_ingredient_prices row and updates
-- shop_recipes.special_ingredient_slots /
-- special_ingredient_slots_i18n for slug = 'zongzi' --
-- it does not touch any other recipe or ingredient row, unlike a full
-- export-shop-content-patch.mjs snapshot.
--
-- NOT verified against production's current state for slug = 'zongzi'.
-- The appended ingredient array below reflects DEV's state at the time this
-- file was generated. If prod has diverged on this specific recipe since
-- then, review this diff carefully before running db:push:prod -- it will
-- overwrite prod's base/special ingredient list for this recipe with the
-- array below, not merge with whatever prod currently has.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'pork-filling',
  7,
  '{"en":"Fresh ground pork","zh":"新鲜猪肉馅"}'::jsonb,
  '/ingredients/ground-pork.png'
)
on conflict (ingredient_key) do nothing;

update shop_recipes
set
  special_ingredient_slots = '[{"ingredientKey":"pork-filling","name":"Fresh ground pork","quantity":1}]'::jsonb,
  special_ingredient_slots_i18n = '{"en":[{"ingredientKey":"pork-filling","name":"Fresh ground pork","quantity":1}],"zh":[{"ingredientKey":"pork-filling","name":"新鲜猪肉馅","quantity":1}]}'::jsonb,
  updated_at = now()
where slug = 'zongzi';

commit;
