-- Create the new "noodle" food (shop_recipes row), plus its new ingredient catalog row(s).
--
-- Generated by the add-food skill. Scoped deliberately: this only inserts
-- one new shop_recipes row and the new ingredient row(s) it introduces -- it does not touch any other recipe or ingredient row.
--
-- NOT separately verified against production for slug = 'noodle'.
-- The recipe insert is a plain INSERT, so it only fails (not silently
-- overwrites) if production already has a row with this slug -- but
-- confirm that's actually true before running db:push:prod. Any new
-- ingredient upserts below use ON CONFLICT DO NOTHING, so they're safe
-- to run even if prod already has that ingredient key from elsewhere.
--
-- This file is NOT applied automatically. Review it, then run:
--   npm run db:push:prod:dry
--   npm run db:push:prod

begin;

-- New ingredient catalog rows this food introduces:
insert into shop_ingredient_prices (
  ingredient_key,
  cost_coins,
  label_i18n,
  icon_path
)
values (
  'tomato',
  5,
  '{"en":"Tomato","zh":"番茄"}'::jsonb,
  '/ingredients/tomato.png'
)
on conflict (ingredient_key) do nothing;

insert into shop_recipes (
  slug, title, title_i18n, display_order, is_active,
  intro, intro_i18n, unlock_cost_coins,
  base_ingredients, base_ingredients_i18n,
  special_ingredient_slots, special_ingredient_slots_i18n,
  variant_icon_rules, cook_method, food_type
)
values (
  'noodle',
  'Plain Noodles',
  '{"en":"Plain Noodles","zh":"阳春面"}'::jsonb,
  11,
  true,
  'A simple bowl of noodles in savory broth, topped with scallions.',
  '{"en":"A simple bowl of noodles in savory broth, topped with scallions.","zh":"一碗简单美味的阳春面，撒上葱花，清香可口。"}'::jsonb,
  20,
  '[{"ingredientKey":"noodles","name":"Noodles","quantity":1},{"ingredientKey":"broth","name":"Broth","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"noodles","name":"Noodles","quantity":1},{"ingredientKey":"broth","name":"Broth","quantity":1}],"zh":[{"ingredientKey":"noodles","name":"面条","quantity":1},{"ingredientKey":"broth","name":"高汤","quantity":1}]}'::jsonb,
  '[{"ingredientKey":"tomato","name":"Tomato","quantity":1},{"ingredientKey":"egg","name":"Egg","quantity":1}]'::jsonb,
  '{"en":[{"ingredientKey":"tomato","name":"Tomato","quantity":1},{"ingredientKey":"egg","name":"Egg","quantity":1}],"zh":[{"ingredientKey":"tomato","name":"番茄","quantity":1},{"ingredientKey":"egg","name":"鸡蛋","quantity":1}]}'::jsonb,
  '[{"match":[],"iconPath":"/rewards/noodle_plain.png"},{"match":["egg","tomato"],"iconPath":"/rewards/noodle_tomato-egg.png","titleI18n":{"en":"Tomato Egg Noodles","zh":"番茄鸡蛋面"}}]'::jsonb,
  'stove',
  'hotmeal'
);

commit;
